### ISSUE TITLE
Create User Login Page

### ISSUE THREAD

**Issue by mkhalid578** [mkhalid578/sw_eng_project#17]
Needs 3 components - 1) Create new user, 2) Enter Company ID and password, 3) Enter user ID and password once company credentials have been accepted

**Comment by vibhutipatel18** [comment]
I have pushed "user-interface-vp" branch which is containing design-project folder. In this folder, html and css file is attached.

**Comment by mkhalid578** [comment]
This is complete and I have reviewed the changes.
