### ISSUE TITLE
Structure database with appropriate tables

### ISSUE THREAD

**Issue by mkhalid578** [mkhalid578/sw_eng_project#6]
Add the necessary tables in the databases needed for application

**Comment by mkhalid578** [comment]
Assigned story to Vibhuti

**Comment by vibhutipatel18** [comment]
Three tables are created. Structure is ready to use.

**Comment by mkhalid578** [comment]
Tables are created. There was an issue when trying to access the item-order table. I have taken out bug for in a separate story.
